# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "ajiechong"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# # file paths
# json_readme_path: './docs/cv-arxiv-daily.json'
# json_gitpage_path: './docs/cv-arxiv-daily-web.json'
# json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

# md_readme_path: 'README.md'
# md_gitpage_path: './docs/index.md'
# md_wechat_path: './docs/wechat.md'

# 输出文件路径
json_output_path: "D:/大三下/科研助手/cs-arxiv-daily.json"
md_readme_path: "D:/大三下/科研助手/README.md"
json_readme_path: "D:/大三下/科研助手/cs-arxiv-daily.json"
json_gitpage_path: "D:/大三下/科研助手/cs-arxiv-daily-web.json"
json_wechat_path: "D:/大三下/科研助手/cs-arxiv-daily-wechat.json"
md_gitpage_path: "D:/大三下/科研助手/index.md"
md_wechat_path: "D:/大三下/科研助手/wechat.md"


# 显示字段配置
show_fields:
  - title       # 论文标题
  - authors     # 作者
  - abstract    # 摘要
  - subjects    # 主题
  - keywords    # 关键词
  - links       # 链接
  

# 排序设置
sort_by: "citations"  # 按被引用量排序
sort_order: "desc"    # 降序排列



# # keywords to search
# keywords:
#     "SLAM": 
#         filters: ["SLAM", "Visual Odometry"]
#     "SFM":
#         filters: ["SFM", "Structure from Motion"]
#     "Visual Localization":
#         filters: ["Visual Localization","Camera Localization",
#                   "Camera Re-localisation","Loop Closure Detection",
#                   "visual place recognition","image retrieval"]
#     "Keypoint Detection":
#         filters: ["Keypoint Detection", "Feature Descriptor"]
#     "Image Matching":
#         filters: ["Image Matching", "Keypoint Matching", 
#                   "Line Segment Detection", "Local Feature Matching"]
#     "NeRF":
#         filters: ["NeRF"]


# CS相关关键词搜索
keywords:
  "Machine Learning":
    filters: ["Machine Learning", "Deep Learning", "Neural Networks"]
  "Natural Language Processing":
    filters: ["NLP", "Natural Language Processing", "Language Models", "Transformers"]
  "Computer Vision":
    filters: ["Computer Vision", "Image Processing", "Object Detection"]
  "SLAM": 
    filters: ["SLAM", "Visual Odometry"]
  "SFM":
    filters: ["SFM", "Structure from Motion"]
  "Visual Localization":
    filters: ["Visual Localization", "Camera Localization", 
              "Camera Re-localisation", "Loop Closure Detection",
              "visual place recognition", "image retrieval"]
  "Keypoint Detection":
    filters: ["Keypoint Detection", "Feature Descriptor"]
  "Image Matching":
    filters: ["Image Matching", "Keypoint Matching", 
              "Line Segment Detection", "Local Feature Matching"]
  "NeRF":
    filters: ["NeRF"]
  "Algorithms":
    filters: ["Algorithms", "Data Structures", "Computational Complexity"]
  "Artificial Intelligence":
    filters: ["AI", "Artificial Intelligence", "Reinforcement Learning"]
  "Human-Computer Interaction":
    filters: ["HCI", "Human-Computer Interaction", "User Interface"]

